import { ModuleDefinition, Theme } from './types';

export const COMMON_SYMBOLS = [
  // Powerline
  { label: 'Right Arrow', value: '', isPowerline: true },
  { label: 'Right Arrow Thin', value: '', isPowerline: true },
  { label: 'Left Arrow', value: '', isPowerline: true },
  { label: 'Left Arrow Thin', value: '', isPowerline: true },
  { label: 'Round Right', value: '', isPowerline: true },
  { label: 'Round Left', value: '', isPowerline: true },
  { label: 'Flame', value: '', isPowerline: true },
  { label: 'Pixelated', value: '', isPowerline: true },
  { label: 'Trapezoid', value: '', isPowerline: true },

  // Powerline Extended (ple- symbols)
  { label: 'Backslash Separator', value: '', isPowerline: true },
  { label: 'Forward Slash Separator', value: '', isPowerline: true },
  { label: 'Flame Thick Mirrored', value: '', isPowerline: true },
  { label: 'Flame Thin', value: '', isPowerline: true },
  { label: 'Flame Thin Mirrored', value: '', isPowerline: true },
  { label: 'Honeycomb', value: '', isPowerline: true },
  { label: 'Honeycomb Outline', value: '', isPowerline: true },
  { label: 'Ice Waveform', value: '', isPowerline: true },
  { label: 'Ice Waveform Mirrored', value: '', isPowerline: true },
  { label: 'Left Half Circle Thin', value: '', isPowerline: true },
  { label: 'Right Half Circle Thin', value: '', isPowerline: true },
  { label: 'Left Hard Divider Inverse', value: '', isPowerline: true },
  { label: 'Right Hard Divider Inverse', value: '', isPowerline: true },
  { label: 'Lego Block Facing', value: '', isPowerline: true },
  { label: 'Lego Block Sideways', value: '', isPowerline: true },
  { label: 'Lego Separator', value: '', isPowerline: true },
  { label: 'Lego Separator Thin', value: '', isPowerline: true },
  { label: 'Lower Left Triangle', value: '', isPowerline: true },
  { label: 'Lower Right Triangle', value: '', isPowerline: true },
  { label: 'Upper Left Triangle', value: '', isPowerline: true },
  { label: 'Upper Right Triangle', value: '', isPowerline: true },
  { label: 'Pixelated Squares Big Mirrored', value: '', isPowerline: true },
  { label: 'Pixelated Squares Small', value: '', isPowerline: true },
  { label: 'Pixelated Squares Small Mirrored', value: '', isPowerline: true },
  { label: 'Trapezoid Top Bottom Mirrored', value: '', isPowerline: true },
  { label: 'Column Number', value: '', isPowerline: true },

  // Common
  { label: 'Arrow', value: '❯' },
  { label: 'Triangle', value: '▶' },
  { label: 'Double Arrow', value: '»' },
  { label: 'Line', value: '─' },
  { label: 'Dot', value: '•' },

  // Nerd Fonts - Dev
  { label: 'Git Branch', value: '' },
  { label: 'Node.js', value: '󰎙' },
  { label: 'Rust', value: '' },
  { label: 'Python', value: '' },
  { label: 'Docker', value: '' },
  { label: 'Package', value: '' },
  { label: 'Go', value: '' },
  { label: 'Java', value: '' },
  { label: 'Ruby', value: '' },
  { label: 'PHP', value: '' },
  { label: 'C', value: '' },
  { label: 'C#', value: '' },
  { label: 'F#', value: '' },
  { label: 'Haskell', value: '' },
  { label: 'Lua', value: '' },
  { label: 'Perl', value: '' },
  { label: 'Swift', value: '' },
  { label: 'Zig', value: '' },

  // Nerd Fonts - System
  { label: 'Home', value: '' },
  { label: 'Folder', value: '' },
  { label: 'Folder Open', value: '' },
  { label: 'Lock', value: '󰌾' },
  { label: 'Time', value: '' },
  { label: 'Battery', value: '🔋' },
  { label: 'Memory', value: '󰍛' },
  { label: 'CPU', value: '' },
  { label: 'Disk', value: '󰋊' },
  { label: 'Network', value: '󰈀' },
  { label: 'Search', value: '' },
  { label: 'Terminal', value: '' },

  // Nerd Fonts - OS
  { label: 'Linux', value: '' },
  { label: 'Apple', value: '' },
  { label: 'Windows', value: '' },
  { label: 'Android', value: '' },
  { label: 'Arch', value: '' },
  { label: 'Debian', value: '' },
  { label: 'Ubuntu', value: '' },
  { label: 'Fedora', value: '' },
  { label: 'Nix', value: '' },

  // Status
  { label: 'Error', value: '✖' },
  { label: 'Success', value: '✔' },
  { label: 'Warning', value: '' },
  { label: 'Info', value: '' },
  { label: 'Question', value: '' },

  // Cloud Services
  { label: 'Cloud', value: '☁️' },
  { label: 'Kubernetes', value: '☸' },
  { label: 'AWS', value: '' },
  { label: 'Azure', value: 'ﴃ' },
  { label: 'GCP', value: '' },
  { label: 'AWS Alt', value: '' },
  { label: 'Google Cloud', value: '' },
  { label: 'Azure DevOps', value: '' },

  // Additional Dev Icons
  { label: 'Git', value: '' },
  { label: 'GitHub', value: '' },
  { label: 'GitLab', value: '' },
  { label: 'Bitbucket', value: '' },
  { label: 'Docker', value: '' },
  { label: 'Kubernetes Alt', value: '' },
  { label: 'Terraform', value: '' },
  { label: 'Helm', value: '' },
  { label: 'Jenkins', value: '' },
  { label: 'CI/CD', value: '' },

  // Database
  { label: 'Database', value: '' },
  { label: 'MySQL', value: '' },
  { label: 'PostgreSQL', value: '' },
  { label: 'MongoDB', value: '' },
  { label: 'Redis', value: '' },
  { label: 'SQLite', value: '' },

  // Monitoring & Observability
  { label: 'Prometheus', value: '' },
  { label: 'Grafana', value: '' },
  { label: 'Datadog', value: '' },
  { label: 'Kibana', value: '' },
  { label: 'Elasticsearch', value: '' },

  // Additional Tools
  { label: 'VS Code', value: '' },
  { label: 'Vim', value: '' },
  { label: 'Neovim', value: '' },
  { label: 'Emacs', value: '' },
  { label: 'Tmux', value: '' },
  { label: 'SSH', value: '' },
  { label: 'Terminal', value: '' },

  // File Types
  { label: 'Config', value: '' },
  { label: 'JSON', value: '' },
  { label: 'YAML', value: '' },
  { label: 'Markdown', value: '' },
  { label: 'PDF', value: '' },
  { label: 'Image', value: '' },
  { label: 'Video', value: '' },
  { label: 'Audio', value: '' },

  // Status & Indicators
  { label: 'Loading', value: '' },
  { label: 'Progress', value: '' },
  { label: 'Warning Alt', value: '' },
  { label: 'Info Alt', value: '' },
  { label: 'Debug', value: '' },
  { label: 'Test', value: '' },
  { label: 'Build', value: '' },

  // Arrows & Separators (Extended)
  { label: 'Double Arrow Right', value: '»' },
  { label: 'Double Arrow Left', value: '«' },
  { label: 'Heavy Arrow Right', value: '➤' },
  { label: 'Heavy Arrow Left', value: '➤' },
  { label: 'Diamond', value: '◆' },
  { label: 'Circle', value: '●' },
  { label: 'Square', value: '■' },
  { label: 'Triangle Up', value: '▲' },
  { label: 'Triangle Down', value: '▼' },
];

export const THEMES: Theme[] = [
  {
    name: 'Default',
    system: 'base16',
    variant: 'dark',
    colors: {
      bg: '#1e1e1e',
      fg: '#d4d4d4',
      black: '#000000',
      red: '#ef4444',
      green: '#22c55e',
      yellow: '#eab308',
      blue: '#3b82f6',
      purple: '#a855f7',
      cyan: '#06b6d4',
      white: '#ffffff',
      orange: '#f97316',
      gray: '#6b7280',
    },
    palette: {
      base00: '#1e1e1e',
      base01: '#2d2d2d',
      base02: '#393939',
      base03: '#515151',
      base04: '#b4b4b4',
      base05: '#d4d4d4',
      base06: '#e6e6e6',
      base07: '#ffffff',
      base08: '#ef4444',
      base09: '#f97316',
      base0A: '#eab308',
      base0B: '#22c55e',
      base0C: '#06b6d4',
      base0D: '#3b82f6',
      base0E: '#a855f7',
      base0F: '#f43f5e',
    }
  },
  {
    name: 'Catppuccin Mocha',
    author: 'https://github.com/catppuccin/catppuccin',
    system: 'base24',
    variant: 'dark',
    colors: {
      bg: '#1e1e2e',
      fg: '#cdd6f4',
      black: '#45475a',
      red: '#f38ba8',
      green: '#a6e3a1',
      yellow: '#f9e2af',
      blue: '#89b4fa',
      purple: '#cba6f7',
      cyan: '#89dceb',
      white: '#bac2de',
      orange: '#fab387',
      gray: '#585b70',
    },
    palette: {
      base00: '#1e1e2e',
      base01: '#181825',
      base02: '#313244',
      base03: '#45475a',
      base04: '#585b70',
      base05: '#cdd6f4',
      base06: '#f5e0dc',
      base07: '#b4befe',
      base08: '#f38ba8',
      base09: '#fab387',
      base0A: '#f9e2af',
      base0B: '#a6e3a1',
      base0C: '#94e2d5',
      base0D: '#89b4fa',
      base0E: '#cba6f7',
      base0F: '#f2cdcd',
      base10: '#1e1e2e',
      base11: '#181825',
      base12: '#313244',
      base13: '#45475a',
      base14: '#585b70',
      base15: '#cdd6f4',
      base16: '#f5e0dc',
      base17: '#b4befe',
    }
  },
  {
    name: 'Tokyo Night',
    system: 'base16',
    variant: 'dark',
    colors: {
      bg: '#1a1b26',
      fg: '#c0caf5',
      black: '#414868',
      red: '#f7768e',
      green: '#9ece6a',
      yellow: '#e0af68',
      blue: '#7aa2f7',
      purple: '#bb9af7',
      cyan: '#7dcfff',
      white: '#a9b1d6',
      orange: '#ff9e64',
      gray: '#565f89',
    },
    palette: {
      base00: '#1a1b26',
      base01: '#16161e',
      base02: '#2f3549',
      base03: '#444b6a',
      base04: '#787c99',
      base05: '#c0caf5',
      base06: '#cbccd1',
      base07: '#d5d6db',
      base08: '#f7768e',
      base09: '#ff9e64',
      base0A: '#e0af68',
      base0B: '#9ece6a',
      base0C: '#7dcfff',
      base0D: '#7aa2f7',
      base0E: '#bb9af7',
      base0F: '#d18616',
    }
  },
  {
    name: 'Gruvbox Dark',
    system: 'base16',
    variant: 'dark',
    colors: {
      bg: '#282828',
      fg: '#ebdbb2',
      black: '#928374',
      red: '#cc241d',
      green: '#98971a',
      yellow: '#d79921',
      blue: '#458588',
      purple: '#b16286',
      cyan: '#689d6a',
      white: '#a89984',
      orange: '#d65d0e',
      gray: '#a89984',
    },
    palette: {
      base00: '#282828',
      base01: '#3c3836',
      base02: '#504945',
      base03: '#665c54',
      base04: '#bdae93',
      base05: '#d5c4a1',
      base06: '#ebdbb2',
      base07: '#fbf1c7',
      base08: '#fb4934',
      base09: '#fe8019',
      base0A: '#fabd2f',
      base0B: '#b8bb26',
      base0C: '#8ec07c',
      base0D: '#83a598',
      base0E: '#d3869b',
      base0F: '#d65d0e',
    }
  },
  {
    name: 'Dracula',
    system: 'base16',
    variant: 'dark',
    colors: {
      bg: '#282a36',
      fg: '#f8f8f2',
      black: '#6272a4',
      red: '#ff5555',
      green: '#50fa7b',
      yellow: '#f1fa8c',
      blue: '#bd93f9',
      purple: '#ff79c6',
      cyan: '#8be9fd',
      white: '#f8f8f2',
      orange: '#ffb86c',
      gray: '#44475a',
    },
    palette: {
      base00: '#282a36',
      base01: '#363447',
      base02: '#44475a',
      base03: '#6272a4',
      base04: '#9ea8c7',
      base05: '#f8f8f2',
      base06: '#f8f8f2',
      base07: '#ffffff',
      base08: '#ff5555',
      base09: '#ffb86c',
      base0A: '#f1fa8c',
      base0B: '#50fa7b',
      base0C: '#8be9fd',
      base0D: '#bd93f9',
      base0E: '#ff79c6',
      base0F: '#ff6e67',
    }
  },
  {
    name: 'Nord',
    author: 'arcticicestudio',
    system: 'base16',
    variant: 'dark',
    colors: {
      bg: '#2E3440',
      fg: '#E5E9F0',
      black: '#3B4252',
      red: '#BF616A',
      green: '#A3BE8C',
      yellow: '#EBCB8B',
      blue: '#81A1C1',
      purple: '#B48EAD',
      cyan: '#88C0D0',
      white: '#ECEFF4',
      orange: '#D08770',
      gray: '#4C566A',
    },
    palette: {
      base00: '#2E3440',
      base01: '#3B4252',
      base02: '#434C5E',
      base03: '#4C566A',
      base04: '#D8DEE9',
      base05: '#E5E9F0',
      base06: '#ECEFF4',
      base07: '#8FBCBB',
      base08: '#BF616A',
      base09: '#D08770',
      base0A: '#EBCB8B',
      base0B: '#A3BE8C',
      base0C: '#88C0D0',
      base0D: '#81A1C1',
      base0E: '#B48EAD',
      base0F: '#5E81AC',
    }
  },
  {
    name: 'Rosé Pine',
    author: 'Emilia Dunfelt <edun@dunfelt.se>',
    system: 'base16',
    variant: 'dark',
    colors: {
      bg: '#191724',
      fg: '#e0def4',
      black: '#26233a',
      red: '#eb6f92',
      green: '#31748f',
      yellow: '#f6c177',
      blue: '#c4a7e7',
      purple: '#c4a7e7',
      cyan: '#9ccfd8',
      white: '#e0def4',
      orange: '#f6c177',
      gray: '#6e6a86',
    },
    palette: {
      base00: '#191724',
      base01: '#1f1d2e',
      base02: '#26233a',
      base03: '#6e6a86',
      base04: '#908caa',
      base05: '#e0def4',
      base06: '#e0def4',
      base07: '#524f67',
      base08: '#eb6f92',
      base09: '#f6c177',
      base0A: '#ebbcba',
      base0B: '#31748f',
      base0C: '#9ccfd8',
      base0D: '#c4a7e7',
      base0E: '#f6c177',
      base0F: '#524f67',
    }
  }
];

export const MODULE_DEFINITIONS: ModuleDefinition[] = [
  // Core/System Modules
  {
    name: 'character',
    description: 'Prompt character',
    defaultProps: {
      format: '$symbol ',
      success_symbol: '[❯](green bold)',
      error_symbol: '[❯](red bold)',
      vicmd_symbol: '[❮](green bold)',
    },
    variables: ['$symbol'],
  },
  {
    name: 'username',
    description: 'Current user name',
    defaultProps: {
      format: '[$user]($style) in ',
      style: 'yellow bold',
      show_always: false,
    },
    variables: ['$user'],
  },
  {
    name: 'hostname',
    description: 'System hostname',
    defaultProps: {
      format: '[$ssh_symbol$hostname]($style) in ',
      style: 'green bold',
      ssh_symbol: '🌐 ',
      ssh_only: true,
    },
    variables: ['$hostname', '$ssh_symbol'],
  },
  {
    name: 'directory',
    description: 'Current directory',
    defaultProps: {
      format: '[$path]($style)[$read_only]($read_only_style) ',
      style: 'cyan bold',
      read_only: ' 󰌾',
      read_only_style: 'red',
      truncation_length: 3,
      truncation_symbol: '…/',
      truncate_to_repo: true,
      substitutions: {},
    },
    variables: ['$path', '$read_only'],
  },
  {
    name: 'cmd_duration',
    description: 'Command duration',
    defaultProps: {
      format: 'took [$duration]($style) ',
      style: 'yellow bold',
      min_time: 2000,
    },
    variables: ['$duration'],
  },
  {
    name: 'line_break',
    description: 'Line break',
    defaultProps: {},
    variables: [],
  },
  {
    name: 'status',
    description: 'Exit status',
    defaultProps: {
      format: '[$symbol$status]($style) ',
      symbol: '❌',
      style: 'red bold',
      disabled: true,
    },
    variables: ['$symbol', '$status'],
  },
  {
    name: 'shell',
    description: 'Active shell',
    defaultProps: {
      format: '[$indicator]($style) ',
      bash_indicator: 'bsh',
      fish_indicator: 'fsh',
      zsh_indicator: 'zsh',
      style: 'cyan bold',
      disabled: true,
    },
    variables: ['$indicator'],
  },
  {
    name: 'time',
    description: 'Current time',
    defaultProps: {
      format: 'at [$time]($style) ',
      style: 'bold yellow',
      time_format: '%T',
      disabled: true,
    },
    variables: ['$time'],
  },
  {
    name: 'shlvl',
    description: 'Shell level',
    defaultProps: {
      format: '[$symbol$shlvl]($style) ',
      symbol: '↕️  ',
      style: 'bold yellow',
      threshold: 2,
      disabled: true,
    },
    variables: ['$symbol', '$shlvl'],
  },
  {
    name: 'jobs',
    description: 'Background jobs',
    defaultProps: {
      format: '[$symbol$number]($style) ',
      symbol: '✦',
      style: 'bold blue',
      number_threshold: 1,
    },
    variables: ['$symbol', '$number'],
  },
  {
    name: 'battery',
    description: 'Battery status',
    defaultProps: {
      format: '[$symbol$percentage]($style) ',
      full_symbol: '🔋',
      charging_symbol: '⚡',
      discharging_symbol: '💀',
      style: 'red bold',
    },
    variables: ['$symbol', '$percentage'],
  },
  {
    name: 'env_var',
    description: 'Environment variable',
    defaultProps: {
      format: 'with [$env_value]($style) ',
      style: 'black bold dimmed',
    },
    variables: ['$env_value'],
  },
  {
    name: 'sudo',
    description: 'Sudo cached',
    defaultProps: {
      format: '[as $symbol]($style)',
      symbol: '🧙 ',
      style: 'bold blue',
      disabled: true,
    },
    variables: ['$symbol'],
  },
  {
    name: 'localip',
    description: 'Local IP',
    defaultProps: {
      format: '[$localipv4]($style) ',
      style: 'yellow bold',
      ssh_only: true,
      disabled: true,
    },
    variables: ['$localipv4'],
  },
  {
    name: 'memory_usage',
    description: 'Memory usage',
    defaultProps: {
      format: 'via [$symbol[$ram( | $swap)]($style) ',
      symbol: '🐏 ',
      style: 'white bold dimmed',
      threshold: 75,
      disabled: true,
    },
    variables: ['$symbol', '$ram', '$swap'],
  },
  {
    name: 'os',
    description: 'Operating system',
    defaultProps: {
      format: '[$symbol]($style)',
      style: 'bold white',
      disabled: true,
      symbols: {},
    },
    variables: ['$symbol'],
  },
  {
    name: 'fill',
    description: 'Fill space',
    defaultProps: {
      symbol: '.',
      style: 'bold black',
    },
    variables: [],
  },
  {
    name: 'text',
    description: 'Static text or symbols',
    defaultProps: {
      format: '',
    },
    variables: [],
  },

  // Git Modules
  {
    name: 'git_branch',
    description: 'Git branch',
    defaultProps: {
      format: 'on [$symbol$branch(:$remote_branch)]($style) ',
      symbol: ' ',
      style: 'purple bold',
      truncation_length: 9223372036854775807,
      truncation_symbol: '…',
    },
    variables: ['$symbol', '$branch', '$remote_branch'],
  },
  {
    name: 'git_commit',
    description: 'Git commit',
    defaultProps: {
      format: '[\\($hash$tag\\)]($style) ',
      style: 'green bold',
      commit_hash_length: 7,
      only_detached: true,
    },
    variables: ['$hash', '$tag'],
  },
  {
    name: 'git_state',
    description: 'Git state',
    defaultProps: {
      format: '\\([$state( $progress_current/$progress_total)]($style)\\) ',
      style: 'yellow bold',
      rebase: 'REBASING',
      merge: 'MERGING',
      revert: 'REVERTING',
      cherry_pick: 'CHERRY-PICKING',
      bisect: 'BISECTING',
      am: 'AM',
      am_or_rebase: 'AM/REBASE',
    },
    variables: ['$state', '$progress_current', '$progress_total'],
  },
  {
    name: 'git_status',
    description: 'Git status',
    defaultProps: {
      format: '([$all_status$ahead_behind]($style) )',
      style: 'red bold',
      conflicted: '🏳',
      ahead: '⇡',
      behind: '⇣',
      diverged: '⇕',
      untracked: '?',
      stashed: '$',
      modified: '!',
      staged: '+',
      renamed: '»',
      deleted: '✘',
    },
    variables: ['$all_status', '$ahead_behind', '$conflicted', '$ahead', '$behind', '$untracked', '$stashed', '$modified', '$staged', '$renamed', '$deleted'],
  },
  {
    name: 'git_metrics',
    description: 'Git metrics',
    defaultProps: {
      format: '([+$added]($added_style) )([-$deleted]($deleted_style) )',
      added_style: 'bold green',
      deleted_style: 'bold red',
      disabled: true,
    },
    variables: ['$added', '$deleted'],
  },
  {
    name: 'hg_branch',
    description: 'Mercurial branch',
    defaultProps: {
      format: 'on [$symbol$branch(:$topic)]($style) ',
      symbol: ' ',
      style: 'bold purple',
    },
    variables: ['$symbol', '$branch', '$topic'],
  },
  {
    name: 'pijul_channel',
    description: 'Pijul channel',
    defaultProps: {
      format: 'on [$symbol$channel]($style) ',
      symbol: ' ',
      style: 'bold purple',
    },
    variables: ['$symbol', '$channel'],
  },
  {
    name: 'fossil_branch',
    description: 'Fossil branch',
    defaultProps: {
      format: 'on [$symbol$branch]($style) ',
      symbol: ' ',
      style: 'bold purple',
    },
    variables: ['$symbol', '$branch'],
  },
  {
    name: 'fossil_metrics',
    description: 'Fossil metrics',
    defaultProps: {
      format: '([+$added]($added_style) )([-$deleted]($deleted_style) )',
      added_style: 'bold green',
      deleted_style: 'bold red',
      disabled: true,
    },
    variables: ['$added', '$deleted'],
  },

  // Language Modules - Popular
  {
    name: 'nodejs',
    description: 'Node.js',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '󰎙 ',
      style: 'bold green',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'python',
    description: 'Python',
    defaultProps: {
      format: 'via [$symbol$pyenv_prefix($version )(\($virtualenv\) )]($style)',
      symbol: ' ',
      style: 'yellow bold',
      pyenv_version_name: false,
      pyenv_prefix: 'pyenv ',
    },
    variables: ['$symbol', '$version', '$virtualenv', '$pyenv_prefix'],
  },
  {
    name: 'rust',
    description: 'Rust',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'bold red',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'golang',
    description: 'Go',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'bold cyan',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'java',
    description: 'Java',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'red dimmed',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'ruby',
    description: 'Ruby',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'bold red',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'php',
    description: 'PHP',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: '147 bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'dotnet',
    description: '.NET',
    defaultProps: {
      format: 'via [$symbol($version )(🎯 $tfm )]($style)',
      symbol: ' ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$version', '$tfm'],
  },
  {
    name: 'c',
    description: 'C/C++',
    defaultProps: {
      format: 'via [$symbol($version(-$name) )]($style)',
      symbol: ' ',
      style: '149 bold',
    },
    variables: ['$symbol', '$version', '$name'],
  },

  // Language Modules - Additional
  {
    name: 'bun',
    description: 'Bun',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🍞 ',
      style: 'bold red',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'deno',
    description: 'Deno',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🦕 ',
      style: 'green bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'elixir',
    description: 'Elixir',
    defaultProps: {
      format: 'via [$symbol($version \\(OTP $otp_version\\) )]($style)',
      symbol: '💧 ',
      style: 'bold purple',
    },
    variables: ['$symbol', '$version', '$otp_version'],
  },
  {
    name: 'erlang',
    description: 'Erlang',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'bold red',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'haskell',
    description: 'Haskell',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: 'λ ',
      style: 'bold purple',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'julia',
    description: 'Julia',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: 'ஃ ',
      style: 'bold purple',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'kotlin',
    description: 'Kotlin',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'lua',
    description: 'Lua',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: ' ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'nim',
    description: 'Nim',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '👑 ',
      style: 'bold yellow',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'ocaml',
    description: 'OCaml',
    defaultProps: {
      format: 'via [$symbol($version )(\\($switch_indicator$switch_name\\) )]($style)',
      symbol: '🐫 ',
      style: 'bold yellow',
    },
    variables: ['$symbol', '$version', '$switch_indicator', '$switch_name'],
  },
  {
    name: 'perl',
    description: 'Perl',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🐪 ',
      style: '149 bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'raku',
    description: 'Raku',
    defaultProps: {
      format: 'via [$symbol($version-$vm_version )]($style)',
      symbol: '🦋 ',
      style: '149 bold',
    },
    variables: ['$symbol', '$version', '$vm_version'],
  },
  {
    name: 'scala',
    description: 'Scala',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🆂 ',
      style: 'red bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'swift',
    description: 'Swift',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🐦 ',
      style: 'bold 202',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'zig',
    description: 'Zig',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '↯ ',
      style: 'bold yellow',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'vlang',
    description: 'V',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: 'V ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'crystal',
    description: 'Crystal',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🔮 ',
      style: 'bold red',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'dart',
    description: 'Dart',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🎯 ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'elm',
    description: 'Elm',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🌳 ',
      style: 'cyan bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'fennel',
    description: 'Fennel',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🧅 ',
      style: 'bold green',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'gleam',
    description: 'Gleam',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '⭐ ',
      style: 'bold #FFAFF3',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'purescript',
    description: 'PureScript',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '<=> ',
      style: 'bold white',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'rlang',
    description: 'R',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '📐 ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'red',
    description: 'Red',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🔺 ',
      style: 'red bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'solidity',
    description: 'Solidity',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: 'S ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'typst',
    description: 'Typst',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: 't ',
      style: '0087BD bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'cobol',
    description: 'COBOL',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '⚙️  ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'daml',
    description: 'Daml',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: 'Λ ',
      style: 'bold cyan',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'haxe',
    description: 'Haxe',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '⌘ ',
      style: 'bold fg:202',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'opa',
    description: 'OPA',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🪖  ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'quarto',
    description: 'Quarto',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '⨁ ',
      style: 'bold #75AADB',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'rye',
    description: 'Rye',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🌾 ',
      style: 'yellow bold',
    },
    variables: ['$symbol', '$version'],
  },

  // Package Managers / Build Tools
  {
    name: 'package',
    description: 'Package version',
    defaultProps: {
      format: 'is [$symbol$version]($style) ',
      symbol: ' ',
      style: '208 bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'cmake',
    description: 'CMake',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '△ ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'conda',
    description: 'Conda',
    defaultProps: {
      format: 'via [$symbol$environment]($style) ',
      symbol: '🅒 ',
      style: 'green bold',
    },
    variables: ['$symbol', '$environment'],
  },
  {
    name: 'meson',
    description: 'Meson',
    defaultProps: {
      format: 'via [$symbol$project]($style) ',
      symbol: '⬢ ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$project'],
  },
  {
    name: 'helm',
    description: 'Helm',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '⎈ ',
      style: 'bold white',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'gradle',
    description: 'Gradle',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🅶 ',
      style: 'bold bright-cyan',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'buf',
    description: 'Buf',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '🐃 ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$version'],
  },

  // Cloud / Infrastructure
  {
    name: 'aws',
    description: 'AWS',
    defaultProps: {
      format: 'on [$symbol($profile )(\\($region\\) )(\\[$duration\\] )]($style)',
      symbol: '☁️  ',
      style: 'bold yellow',
    },
    variables: ['$symbol', '$profile', '$region', '$duration'],
  },
  {
    name: 'azure',
    description: 'Azure',
    defaultProps: {
      format: 'on [$symbol($subscription )]($style)',
      symbol: 'ﴃ ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$subscription'],
  },
  {
    name: 'gcloud',
    description: 'Google Cloud',
    defaultProps: {
      format: 'on [$symbol$account(@$domain)(\\($region\\))]($style) ',
      symbol: '☁️  ',
      style: 'bold blue',
    },
    variables: ['$symbol', '$account', '$domain', '$region', '$project'],
  },
  {
    name: 'openstack',
    description: 'OpenStack',
    defaultProps: {
      format: 'on [$symbol$cloud(\\($project\\))]($style) ',
      symbol: '☁️  ',
      style: 'bold yellow',
    },
    variables: ['$symbol', '$cloud', '$project'],
  },
  {
    name: 'docker_context',
    description: 'Docker',
    defaultProps: {
      format: 'via [$symbol$context]($style) ',
      symbol: ' ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$context'],
  },
  {
    name: 'kubernetes',
    description: 'Kubernetes',
    defaultProps: {
      format: '[$symbol$context( \\($namespace\\))]($style) in ',
      symbol: '☸ ',
      style: 'cyan bold',
      disabled: true,
    },
    variables: ['$symbol', '$context', '$namespace'],
  },
  {
    name: 'terraform',
    description: 'Terraform',
    defaultProps: {
      format: 'via [$symbol$workspace]($style) ',
      symbol: '💠 ',
      style: 'bold 105',
    },
    variables: ['$symbol', '$workspace', '$version'],
  },
  {
    name: 'pulumi',
    description: 'Pulumi',
    defaultProps: {
      format: 'via [$symbol($username@)$stack]($style) ',
      symbol: ' ',
      style: 'bold 5',
    },
    variables: ['$symbol', '$stack', '$username', '$version'],
  },

  // Container / Virtualization
  {
    name: 'container',
    description: 'Container',
    defaultProps: {
      format: '[$symbol \\[$name\\]]($style) ',
      symbol: ' ',
      style: 'red bold dimmed',
    },
    variables: ['$symbol', '$name'],
  },
  {
    name: 'singularity',
    description: 'Singularity',
    defaultProps: {
      format: '[$symbol\\[$env\\]]($style) ',
      symbol: '',
      style: 'blue bold dimmed',
    },
    variables: ['$symbol', '$env'],
  },
  {
    name: 'vagrant',
    description: 'Vagrant',
    defaultProps: {
      format: 'via [$symbol($version )]($style)',
      symbol: '⍱ ',
      style: 'cyan bold',
    },
    variables: ['$symbol', '$version'],
  },
  {
    name: 'nix_shell',
    description: 'Nix shell',
    defaultProps: {
      format: 'via [$symbol$state( \\($name\\))]($style) ',
      symbol: '❄️  ',
      style: 'bold blue',
      impure_msg: 'impure',
      pure_msg: 'pure',
    },
    variables: ['$symbol', '$state', '$name'],
  },
  {
    name: 'guix_shell',
    description: 'Guix shell',
    defaultProps: {
      format: 'via [$symbol]($style) ',
      symbol: '🐃 ',
      style: 'yellow bold',
    },
    variables: ['$symbol'],
  },
  {
    name: 'spack',
    description: 'Spack',
    defaultProps: {
      format: 'via [$symbol$environment]($style) ',
      symbol: '🅢 ',
      style: 'blue bold',
    },
    variables: ['$symbol', '$environment'],
  },

  // Other Tools
  {
    name: 'direnv',
    description: 'direnv',
    defaultProps: {
      format: '[$symbol$loaded/$allowed]($style) ',
      symbol: '📂 ',
      style: 'bold orange',
      disabled: true,
    },
    variables: ['$symbol', '$loaded', '$allowed'],
  },
  {
    name: 'vcsh',
    description: 'vcsh',
    defaultProps: {
      format: 'vcsh [$symbol$repo]($style) ',
      symbol: '',
      style: 'bold yellow',
    },
    variables: ['$symbol', '$repo'],
  },

  // Custom
  {
    name: 'custom',
    description: 'Custom module',
    defaultProps: {
      format: '[$symbol($output )]($style)',
      symbol: '',
      style: 'green bold',
    },
    variables: ['$symbol', '$output'],
  },
  {
    name: 'text',
    description: 'Static Text',
    defaultProps: {
      format: '$text',
      text: '',
      style: '',
    },
    variables: ['$text'],
  },
];

// Mock data for previewing the prompt
export const MOCK_DATA: Record<string, any> = {
  character: {
    $symbol: '❯',
  },
  username: {
    $user: 'developer',
  },
  hostname: {
    $hostname: 'workstation',
    $ssh_symbol: '🌐 ',
  },
  directory: {
    $path: '~/projects/starship-architect',
    $read_only: ' 󰌾',
  },
  git_branch: {
    $symbol: ' ',
    $branch: 'main',
    $remote_branch: 'origin/main',
  },
  git_commit: {
    $hash: '8c9acbe',
    $tag: '',
  },
  git_state: {
    $state: 'REBASING',
    $progress_current: '2',
    $progress_total: '5',
  },
  git_status: {
    $all_status: '!?',
    $ahead_behind: '⇡1',
    $conflicted: '',
    $ahead: '⇡1',
    $behind: '',
    $untracked: '?',
    $stashed: '',
    $modified: '!',
    $staged: '+',
    $renamed: '',
    $deleted: '',
  },
  git_metrics: {
    $added: '12',
    $deleted: '5',
  },
  nodejs: {
    $symbol: '󰎙 ',
    $version: 'v20.10.0',
  },
  python: {
    $symbol: ' ',
    $version: '3.12.1',
    $virtualenv: 'venv',
    $pyenv_prefix: '',
  },
  rust: {
    $symbol: ' ',
    $version: '1.75.0',
  },
  golang: {
    $symbol: ' ',
    $version: '1.21.5',
  },
  java: {
    $symbol: ' ',
    $version: '21.0.1',
  },
  ruby: {
    $symbol: ' ',
    $version: '3.2.2',
  },
  php: {
    $symbol: ' ',
    $version: '8.3.0',
  },
  dotnet: {
    $symbol: ' ',
    $version: '8.0.100',
    $tfm: 'net8.0',
  },
  docker_context: {
    $symbol: ' ',
    $context: 'default',
  },
  kubernetes: {
    $symbol: '☸ ',
    $context: 'dev-cluster',
    $namespace: 'default',
  },
  aws: {
    $symbol: '☁️  ',
    $profile: 'dev',
    $region: 'us-east-1',
    $duration: '2h',
  },
  azure: {
    $symbol: 'ﴃ ',
    $subscription: 'Production',
  },
  gcloud: {
    $symbol: '☁️  ',
    $account: 'user@example.com',
    $domain: 'example.com',
    $region: 'us-central1',
    $project: 'my-project',
  },
  cmd_duration: {
    $duration: '2.5s',
  },
  time: {
    $time: '13:37:42',
  },
  battery: {
    $symbol: '🔋',
    $percentage: '85%',
  },
  status: {
    $symbol: '❌',
    $status: '1',
  },
  jobs: {
    $symbol: '✦',
    $number: '2',
  },
  package: {
    $symbol: ' ',
    $version: '1.2.3',
  },
  terraform: {
    $symbol: '💠 ',
    $workspace: 'production',
    $version: '1.6.5',
  },
};
